# Generated by Django 3.2 on 2023-08-13 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='image',
        ),
    ]
